export enum Routes {
    AUTH = 'auth',
    USERS = 'users',
    CONVERSATIONS = 'conversations',
    MESSAGES = 'conversations/:id/messages',
    GROUPS = 'groups',
    GROUP_MESSAGES = 'groups/:id/messages',
    GROUP_RECIPIENTS = 'groups/:id/recipients',
    FRIENDS = 'friends',
    FRIEND_REQUESTS = 'friend-requests',
    USER_PROFILE = 'user-profile',
}

export enum Services {
    AUTH = 'AUTH_SERVICE',
    USERS = 'USERS_SERVICE',
    CONVERSATIONS = 'CONVERSATIONS_SERVICE',
    MESSAGES = 'MESSAGES_SERVICE',
    GATEWAY_SESSION_MANAGER = 'GATEWAY_SESSION_MANAGER',
    GROUPS = 'GROUPS_SERVICE',
    GROUP_MESSAGES = 'GROUP_MESSAGES_SERVICE',
    GROUP_RECIPIENTS = 'GROUP_RECIPIENTS_SERVICE',
    SPACES_CLIENT = 'SPACES_CLIENT',
    IMAGE_UPLOAD_SERVICE = 'IMAGE_UPLOAD_SERVICE',
    FRIENDS = 'FRIENDS_SERVICE',
    FRIEND_REQUESTS = 'FRIEND_REQUESTS_SERVICE',
    USER_PROFILE = 'USER_PROFILE_SERVICE',
}
